germanWordList = [
  [ 'to be', 'sein' ],
  [ 'to become', 'werden' ],
  [ 'to have', 'haben' ],
  [ 'to be able to', 'können' ],
  [ 'to must', 'müssen' ],
  [ 'to give', 'geben' ],
  [ 'should', 'sollen' ],
  [ 'to say', 'sagen' ],
  [ 'to want', 'wollen' ],
  [ 'to come', 'kommen' ],
  [ 'to go/to walk', 'gehen' ],
  [ 'to do', 'machen' ],
  [ 'to stand', 'stehen' ],
  [ 'to see', 'sehen' ],
  [ 'to find', 'finden' ],
  [ 'to stay', 'bleiben' ],
  [ 'to lie', 'liegen' ],
  [ 'to put', 'stellen' ],
  [ 'to take', 'nehmen' ],
  [ 'to be allowed', 'dürfen' ],
  [ 'to bring', 'bringen' ],
  [ 'to hold', 'halten' ],
  [ 'to explain', 'erklären' ],
  [ 'to play', 'spielen' ],
  [ 'to be called', 'heißen' ],
  [ 'to know', 'wissen' ],
  [ 'to belong', 'hehören' ],
  [ 'to begin', 'beginnen' ],
  [ 'to speak', 'sprechen' ],
  [ 'to do', 'tun' ],
  [ 'to like', 'mögen' ],
  [ 'to win', 'gewinnen' ],
  [ 'to get', 'bekommen' ],
  [ 'to write', 'schreiben' ],
  [ 'to work', 'arbeiten' ],
  [ 'to meet', 'treffen' ],
  [ 'to pay', 'zahlen' ],
  [ 'to live', 'leben' ],
  [ 'to walk', 'laufen' ],
  [ 'to need', 'brauchen' ],
  [ 'to celebrate', 'feiern' ],
  [ 'to drive, ride', 'fahren' ],
  [ 'to search', 'suchen' ],
  [ 'to put', 'legen' ],
  [ 'to believe', 'glauben' ],
  [ 'to seem', 'scheinen' ],
  [ 'to lack, to be missing', 'fehlen' ],
  [ 'to know', 'kennen' ],
  [ 'to ask', 'fragen' ]
]

fruits = [
  ['apple','elma'],
  ['pear','armut'],
  ['watermelon','karpuz'],
  ['pineapple','ananas'],
  ['strawberry','çilek'],
  ['banana','muz'],
  ['lemon','limon'],
  ['kiwi','kivi'],
  ['grape','üzüm'],
  ['apricot','kayısı'],
  ['peach','şeftali'],
  ['blackberry','böğürtlen'],
  ['cherry','kiraz'],
  ['hazelnut','fındık'],
  ['melon','kavun'],
  ['orange','portakal'],
  ['plum','erik'],
  ['mandarin','mandalina'],
  ['fig','incir'],
  ['date','hurma'],
  ['parsimmon','trabzon hurması'],
  ['carrot','havuç'],
  ['pumpkin','balkabağı']
]